# Project information
site_name: 'BigGIS - Scalable GIS for Predictive and Prescriptive Analytics'
site_description: 'Central documentation of the BigGIS project'
site_author: 'BigGIS Team'

# tracking code and hostname
google_analytics: ['UA-112317697-1', 'biggis-project.eu']

# You can set the 'site_url' parameter explicitly, otherwise it points to the documentation root
#site_url: 'http://biggis-project.eu/biggis-docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/biggis-project'

# You can disable edit icon for pages by setting edit_uri:"", otherwise it points to github
edit_uri: ""


# Copyright
copyright: '
  <a href="https://www.fzi.de/footer/impressum/">
    <b>Impressum:</b> FZI Forschungszentrum Informatik am Karlsruher Institut für Technologie.</a>
    <br/>
    <b>FKZ: 01IS14012</b>
    - BigGIS website maintained by <b><a href="https://github.com/vsimko">Viliam Simko</a></b>
'

#copyright: 'Copyright &copy; 2017 - 2021 SeRoNet Project'

# Documentation and theme
theme:
  name: material
  custom_dir: 'custom_theme'
  favicon: favicon.ico # this icon appears in the browser's tab
  logo: favicon.svg # this icon appears in the top left corner on each page
  palette:
    primary: 'dark blue'
    accent: 'blue'
  feature:
      tabs: true

extra:
  # disqus: 'biggis-docs'
  social: # see http://fontawesome.io/icons/ for allowed 'type' values
    - type: 'globe'
      link: 'http://biggis-project.eu'
    - type: 'github'
      link: 'https://github.com/biggis-project'

# Extensions
markdown_extensions:
  - pyembed.markdown:           # https://pyembed.github.io/usage/markdown/
  - footnotes:                  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - admonition:                 # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - meta:                       # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - pymdownx.arithmatex:        # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#arithmatex-mathjax
  - pymdownx.smartsymbols:      # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#smartsymbols
      copyright: false
  - pymdownx.superfences:       # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.details:           # https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.magiclink:         # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
      repo_url_shortener: true
  - codehilite:                 # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      guess_lang: false
  - toc:
      permalink: true

extra_javascript:
  - 'extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML'
  - 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'

extra_css:
  - 'animations.css'

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
