# Project information
site_name: 'BigGIS Documentation'
site_description: 'Central documentation of the BigGIS project'
site_author: 'BigGIS Team'

# tracking code and hostname
google_analytics: ['UA-112317697-1', 'biggis-project.eu']

# You can set the 'site_url' parameter explicitly, otherwise it points to the documentation root
#site_url: 'http://biggis-project.eu/biggis-docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/biggis-project'

# You can disable edit icon for pages by setting edit_uri:"", otherwise it points to github
#edit_uri: ""


# Copyright
copyright: '
  <a href="https://www.fzi.de/footer/impressum/">
    <b>Impressum:</b> FZI Forschungszentrum Informatik am Karlsruher Institut für Technologie.</a>
    <br/>
  <b>FKZ: 01IS14012</b>
'

#copyright: 'Copyright &copy; 2017 - 2021 SeRoNet Project'

# Documentation and theme
theme:
  name: material
  favicon: favicon.ico # this icon appears in the browser's tab
  logo: favicon.svg # this icon appears in the top left corner on each page
  palette:
    primary: 'dark blue'
    accent: 'blue'
  feature:
      tabs: true

extra:
  social: # see http://fontawesome.io/icons/ for allowed 'type' values
      - type: 'globe'
        link: 'http://biggis-project.eu'
      - type: 'github'
        link: 'https://github.com/biggis-project'

# Extensions
markdown_extensions:
  - footnotes:                  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - admonition:                 # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.arithmatex:        # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#arithmatex-mathjax
  - pymdownx.smartsymbols:      # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#smartsymbols
  - pymdownx.superfences:       # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.magiclink:         # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
      repo_url_shortener: true
  - codehilite:                 # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      guess_lang: false
  - toc:
      permalink: true

extra_javascript:
  - 'extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML'
  - 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'

pages:
  - About BigGIS: ./index.md
  - Architecture:
      - Overview: ./architecture/index.md
      - Components: ./architecture/Docker_Containers.md
      - Platform bwCloud: ./architecture/Platform_bwCloud/index.md
      - StreamPipes: ./architecture/StreamPipes/index.md
  - Project Consortium: ./consortium.md
  - Contributing: ./contributing.md
  - Data sources:
      - Datasets in BigGIS: ./data-sources/index.md
      - Weather stations: ./data-sources/weather-stations.md
  - Demos:
      - About demos: ./demos/index.md
      - EnviroCar (Smart City): ./demos/enviro-car.md
      - Gas Cloud Detection: ./demos/gas-detect.md
      - Gas Cloud Prediction: ./demos/gas-predict.md
      - Heatstress Routing App: ./demos/heatstress.md
      - Hotspot analysis (using G*): ./demos/hotspot_analysis/index.md
      - Invasive species: ./demos/invasive-spec.md
      - Landuse classification: ./demos/landuse.md
      - OpticalRemoteSensing:
          - Optical Remote Sensing: ./demos/opticalRemoteSensing/index.md
          - Gas-detect: ./demos/opticalRemoteSensing/gas-detect.md
      - Optimal flight plan for drones: ./demos/optimize-drones.md
      - Placement of sensors under uncertainty: ./demos/optimize-sensors.md
      - Stability of hotspots: ./demos/stability_of_hotspots/index.md
      - Urban Heat Islands: ./demos/urban-heat-islands.md
      - Visual Analysis of Spatio-Temporal Event Predictions: ./demos/visual-analysis-of-uhi.md
  - Documentation Howto: ./docs-howto.md
  - Methods:
      - About Method: ./methods/index.md
      - Focal Getis-ord: ./methods/focal_getis_ord.md
      - Foal Getis-ord on rasters: ./methods/focal_getis_ord_raster.md
      - Standards Getis-Ord G*: ./methods/getis_ord.md
      - Getis-ord G* on rasters: ./methods/getis_ord_raster.md
      - One vs. Rest: ./methods/one_vs_rest.md
      - Stability of hotspots: ./methods/soh.md
      - Triangular Chlorophyll Index (TCI) in Spectral Remote Sensing: ./methods/spectralAnalysisTCI.md
      - Support Vector Machine: ./methods/support_vector_machine.md
  - Scenarios:
      - Smart City: ./scenarios/01_city.md
      - Disaster Management: ./scenarios/02_bos.md
      - Environment: ./scenarios/03_env.md

